influxdb:
  image: influxdb
  container_name: influxdb
  restart: always
  ports:
    - "8086:8086"
  volumes:
    - "/data/influxdb:/var/lib/influxdb"

telegraf:
  image: nuntz/telegraf-snmp
  container_name: telegraf
  restart: always
  ports:
    - "8083:8083"
  links:
    - influxdb
  volumes:
    - "/data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf" 

grafana:
  image: grafana/grafana
  container_name: grafana
  restart: always
  ports:
    - "80:3000"
  volumes:
    - "/data/grafana:/var/lib/grafana"
  links:
    - influxdb
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=password
